<?php

declare(strict_types=1);

namespace Temkaa\Botifier\Service;

use Http\Message\MultipartStream\MultipartStreamBuilder;
use JsonException;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\StreamFactoryInterface;
use SensitiveParameter;
use Temkaa\Botifier\Factory\ResponseFactory;
use Temkaa\Botifier\Interface\RequestInterface;
use Temkaa\Botifier\Interface\ResponseInterface;
use Temkaa\Botifier\Model\Response\Nested\Update;
use Temkaa\Botifier\Model\Shared\InputFile;

/**
 * @api
 */
final readonly class TelegramClient implements TelegramClientInterface
{
    private const string BASE_URL = 'https://api.telegram.org';

    public function __construct(
        private ClientInterface $httpClient,
        private RequestFactoryInterface $httpRequestFactory,
        private StreamFactoryInterface $httpStreamFactory,
        private ResponseFactory $responseFactory,
        #[SensitiveParameter] private string $token,
    ) {
    }

    public function reply(RequestInterface $request, Update $update): ResponseInterface
    {
        return $this->sendRequest($request, $update);
    }

    public function send(RequestInterface $request): ResponseInterface
    {
        return $this->sendRequest($request);
    }

    /**
     * @throws ClientExceptionInterface
     * @throws JsonException
     */
    private function sendRequest(RequestInterface $request, ?Update $replyTo = null): ResponseInterface
    {
        // ./vendor/bin/botifier-stub-generator botifier:generate:stubs --model-namespace=Temkaa\\Botifier\\Model --model-path=src/Model --interface-namespace=Temkaa\\Botifier\\Interface --interface-path=src/Interface --enum-namespace=Temkaa\\Botifier\\Enum --enum-path=src/Enum --trait-namespace=Temkaa\\Botifier\\Trait --trait-path=src/Trait --factory-namespace=Temkaa\\Botifier\\Factory --factory-path=src/Factory

        // TODO: delete format interface (or not delete?)
        // TODO: annotate models, factories, interfaces, traits with @api attribute
        // TODO: add update type autogenerated enum
        // TODO: add raw to responses?
        $url = sprintf('%s/bot%s/%s', self::BASE_URL, $this->token, $request->getApiMethod()->value);

        $data = $replyTo
            ? [...$request->getData(), 'reply_to_message_id' => $replyTo->updateId]
            : $request->getData();

        /** @var array<string, InputFile> $files */
        $files = [];

        foreach ($data as $name => $value) {
            if ($value instanceof InputFile) {
                $files[$name] = $value;
                unset($data[$name]);
            }
        }

        if ($files) {
            $multipartStreamBuilder = new MultipartStreamBuilder($this->httpStreamFactory);

            foreach ($data as $name => $value) {
                $multipartStreamBuilder->addResource(
                    $name,
                    is_string($value) ? $value : json_encode($value, JSON_THROW_ON_ERROR),
                );
            }
            foreach ($files as $name => $file) {
                $fileName = $file->getFileName();
                $fileNameInfo = $fileName !== null ? ['filename' => $fileName] : [];

                $multipartStreamBuilder->addResource($name, $file->getContent(), $fileNameInfo);
            }

            $body = $multipartStreamBuilder->build();
            $contentType = sprintf(
                'multipart/form-data; boundary=%s; charset=utf-8',
                $multipartStreamBuilder->getBoundary(),
            );
        } else {
            $body = $this->httpStreamFactory->createStream(json_encode($data, JSON_THROW_ON_ERROR));

            $contentType = 'application/json; charset=utf-8';
        }

        $httpRequest = $this->httpRequestFactory
            ->createRequest($request->getHttpMethod()->value, $url)
            ->withBody($body)
            ->withHeader('Content-Type', $contentType)
            ->withHeader('Content-Length', (string) $body->getSize());

        $response = $this->httpClient->sendRequest($httpRequest);

        return $this->responseFactory->create(
            $request->getApiMethod(),
            $response->getBody()->getContents(),
        );
    }
}
